#!/bin/bash -le

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config
source ${SOURCE_DIR}/python/deploy

cat >${APP_DIR}/start_app.bash <<EOF
#!/bin/bash -le

exec $(cat ${CURRENT_DIR}/Procfile | grep "web:" | sed -e 's/web: //')
EOF

chmod +x ${APP_DIR}/start_app.bash

sed -i 's;^web: .*;web: sudo /usr/bin/supervisord;' ${CURRENT_DIR}/Procfile
